language: python

python:
- '3.6'
- '3.7'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install pyyaml # For yaml storing

script:
- pre-commit run --all-files
- poetry run pytest

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
